### PR TITLE
dependencies explicitly required to avoid load order issues

### LINKED ISSUE #14: Implicit Load Order dependency
`app/decorators/controllers/spree/user_sessions_controller_decorator.rb` and
`app/decorators/controllers/spree/amin/user_sessions_controller_decorator.rb`

both require that
`app/decorators/controllers/action_controller_base_decorator.rb`
is loaded first.

This normally seems to happen, but not in all cases. However I have machines with the same project setup where the following exception occurs:
```
[...]
.rbenv/versions/2.5.1/gemsets/rails52/bundler/gems/spree-refinery-authentication-da83d4dbd36b/app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb:2:in 'block in <main>'
[...]
/.rbenv/versions/2.5.1/gemsets/rails52/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:701:in 'block (2 levels) in skip_callback': Before process_action callback :detect_spreefinery_single_sign_on! has not been defined (ArgumentError)
```

Not sure how the load order of the classes in a gem are defined in Rails, however an explicit reference
`require_relative '../../action_controller_base_decorator.rb'`
in
`app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb` resolves the issue.

I think this can be resolved better, however, if a PR helps let me know.

### PR DESCRIPTION
**Pull request by Obi-TOB**
This should fix #14

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -19,4 +19,5 @@ tmp
 
 .gems
 .ruby-version
-.rbenv-gemsets
\ No newline at end of file
+.rbenv-gemsets
+.idea/
```
Comment (bricesanchez) [inline .gitignore]: You should not commit this in our public repo

File: app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb [hunk 2]
```diff
@@ -1,3 +1,5 @@
+require_relative '../../action_controller_base_decorator.rb'
+
 Spree::Admin::UserSessionsController.class_eval do
```
Comment (bricesanchez) [inline app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb:3]: Do you think you could refactor this without `class_eval` ?

**Review by bricesanchez — CHANGES_REQUESTED** [review]

File: app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb (hunk 2 above)
Comment (Obi-TOB) [reply app/decorators/controllers/spree/admin/user_sessions_controller_decorator.rb:3]: Not sure
- how you would want to do this? In any case you need to add functionality to the UserSessionController. That's nothing that I added.
- how this would affect the load issue topic, as it would still need to load action_controller_base_decorator.rb first to have access to `:detect_spreefinery_single_sign_on!`

File: .gitignore (hunk 1 above)
Comment (Obi-TOB) [reply .gitignore]: I reverted this to previous .gitignore version

**Review by bricesanchez — APPROVED** [review]

**Comment by bricesanchez** [comment]
Hi @Obi-TOB,

Sorry i've missed this PR.

Thanks for your contribution!
